#!/bin/dash


m=$1

file_name=$(echo "$m" | cut -d ':' -f2)
version=$(echo "$m" | cut -d ':' -f1)


#echo file_name $file_name
#echo version$version


#if the verison is not specified - such as :a 
if [ "$version" = "" ] 
then 
    #echo index
    #check if the file exists in .index dir 
    if [ ! -e .shrug/.index/$file_name ]
    then
        echo "shrug-show: error: '$file_name' not found in index"
    else
        cat .shrug/.index/$file_name
    fi
    
else
    #echo commit
    #check if the commit version exists
    #if commit version exists, check if the file exists 
    #if both exists, cat the file out
    if [ ! -d .shrug/"commit.$version" ]
    then 
        echo "shrug-show: error: unknown commit '$version'"
    elif [ ! -e .shrug/"commit.$version"/$file_name ]
    then 
        echo "shrug-show: error: '$file_name' not found in commit $version"
    else 
        cat .shrug/"commit.$version"/$file_name
    fi
fi 

#error handling 




